config/routes.rb
BookmarkKeeper::Application.routes.draw do
  devise_for :users, controllers:{ registrations: "registrations",
                     :omniauth_callbacks => "omniauth_callbacks" }
  resources :categories

  resources :bookmarks

   root 'welcome#index'
   post "versions/:id/revert" => "versions#revert", :as => "revert_version"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :bookmarks, dependent: :destroy
  belongs_to :user
  
  validates :name, length: { in: 3..50 }, presence: true
  validates :user_id, presence: true

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = current_user.categories.order("name")
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @bookmarks = @category.bookmarks.paginate(:page => params[:page], per_page: 15).order('created_at DESC') 
  end

  # GET /categories/new
  def new
    @category = current_user.categories.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to request.referrer, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to root_path}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = current_user.categories.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<% if category.bookmarks.any? %>
  <li class="list-group-item">
    <div class="well well-sm">
    <h2><%= category.name %></h2>
  </div>


    <ul class="list-group">
    <% category.bookmarks.last(5).reverse.each do |bookmark|%> 
     <li class="list-group-item">
      <h2><%= link_to bookmark.title, bookmark.url, target: "_blank" %></h2>
      <div class="bookmark">
      <p><%= truncate(strip_tags(bookmark.description), length: 250) %></p>
  <div>
  <%=link_to t('bookmarks.bookmark.show'), bookmark_path(bookmark), class: "btn btn-default btn-xs" %>
  <%=link_to t('bookmarks.show.edit'), edit_bookmark_path(bookmark), class: "btn btn-default btn-xs" %>
  <%=link_to t('bookmarks.show.destroy'), bookmark_path(bookmark), :method => 'delete', class: "btn btn-danger btn-xs" %>
  </div>
  <small><em><%= bookmark.timestamp %></em></small>
</div>
</li>

    <% end %>

    </ul>
      <%= link_to t('.more'), category_path(category)%>
  </li>
  <% end %>

app/views/categories/_form.html.erb
<%= simple_form_for @category, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f| %>
	<div class="form-group">
    <%= f.input :name, input_html: { class: "form-control" } %>
  </div>
  <div class="form-group">
    <div class="container">
      <%= f.button :submit, :class => 'btn-primary' %>
      <%= link_to t('.cancel'),
                  categories_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header panel panel-default">
	<div class="panel-heading">
  	<h1><%=t('.title')%></h1>
	</div>
	<div class="panel-body">
		<%= render :partial => 'form' %>
	</div>
</div>

app/views/categories/index.html.erb
<div class="page-header">
  <h1><%=t('.title') %></h1>
</div>

<%= link_to t('.new'), new_category_path, :class => 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('.name') %></th>
      <th><%= t('.created_at') %></th>
      <th><%= t(".actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
          <td><%=link_to category.name, category_path(category)%></td>
        <td><%=l category.created_at, format: :long %></td>
        <td>
          <%= link_to edit_category_path(category), :class => 'btn btn-xs', :title => "#{ t('.edit')}" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to category_path(category), :method => :delete, :data => { :confirm => t('.confirm') }, 
              :class => 'btn btn-xs', :title => "#{ t('.destroy')}" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header panel panel-default">
	<div class="panel-heading">
  	<h1><%=t('.title')%></h1>
	</div>
	<div class="panel-body">
		<%= render :partial => 'form' %>
	</div>
</div>

app/views/categories/show.html.erb
<div class="page-header">
  <h1><%= t('.title') %> <%= @category.name %></h1>
</div>

<div class="form-group">
  <%= link_to t('.back'),
              categories_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit'),
              edit_category_path(@category), :class => 'btn btn-default' %>
  <%= link_to t('.destroy'),
              category_path(@category),
              :method => 'delete',
              :data => { :confirm => t('.confirm') },
              :class => 'btn btn-danger' %>
</div>


<div id="my-bookmarks">
  <%= render @bookmarks, show_category: false %>
</div>
 
<div id="infinite-scrolling">
  <%= will_paginate @bookmarks %>
</div>

app/views/categories/show.js.erb
$('#my-bookmarks').append('<%= j render @bookmarks, show_category: false %>');
<% if @bookmarks.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @bookmarks %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>