config/routes.rb
BookmarkKeeper::Application.routes.draw do
  devise_for :users, controllers:{ registrations: "registrations",
                     :omniauth_callbacks => "omniauth_callbacks" }
  resources :categories

  resources :bookmarks

   root 'welcome#index'
   post "versions/:id/revert" => "versions#revert", :as => "revert_version"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <%= viewport_meta_tag %>
    <title><%= content_for?(:title) ? yield(:title) : "BookmarkKeeper" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">BookmarkKeeper</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
            <%= render_navigation :expand_all => true, :renderer => :bootstrap if user_signed_in? %>
           
           
      
            <ul class='nav navbar-nav navbar-right'>
              <li>
                  <%=  link_to 'Add Bookmark', new_bookmark_path %>
              </li>
              <li>
                   <%= form_tag bookmarks_path, :method => 'get', :class => "navbar-form navbar-left", :role => 'search' do %>
                <div class="form-group">
                  <%= text_field_tag :search, params[:search], :class => "form-control", :placeholder => "Search Bookmarks" %>
                </div>
                  <%= submit_tag "Search", :name => nil, :class => "btn btn-default" %>
              <% end %>
              </li>
            </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-md-9">
          <span class="text-center"><%= bootstrap_flash %></span>
          <%if !user_signed_in? %>
            <h2 class="text-center">Keep your bookmarks in your reach zone!</h2>
          <%end%>
          <%= yield %>
        </div>
        <% if user_signed_in? %>
        <div class="col-md-3">
          <div class="well sidebar-nav">
            <h3>Last Added</h3>
            <ul class="nav nav-list">
              <% current_user.bookmarks.last(3).reverse.each do |b|%>
                <li><%= link_to b.title, b.url, :target => '_blank' %></li>
              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
              <%end%>
      </div><!--/row-->

      <footer>
        <p>&copy; mgb313 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>